import re

from django import forms

from .models import ClientPanel, OLT, SubscriptionPlan, UserProfile
from .utils import generate_snmp_community

HUAWEI_HARDWARE_CHOICES = [
    ("", "Select Huawei OLT hardware"),
    ("MA5608T", "Huawei MA5608T"),
    ("MA5608", "Huawei MA5608"),
    ("MA5603T", "Huawei MA5603T"),
    ("MA5603", "Huawei MA5603"),
    ("MA5680T", "Huawei MA5680T"),
    ("MA5683T", "Huawei MA5683T"),
    ("MA5683", "Huawei MA5683"),
    ("MA5800-X2", "Huawei MA5800-X2"),
    ("MA5800-X7", "Huawei MA5800-X7"),
    ("MA5800-X15", "Huawei MA5800-X15"),
    ("MA5800-X17", "Huawei MA5800-X17"),
]

SNMP_SETUP_CHOICES = [
    ("manual", "I will enter SNMP strings manually"),
    ("generate", "Generate read/write strings and push to OLT"),
]


class OLTForm(forms.ModelForm):
    snmp_mode = forms.ChoiceField(
        choices=SNMP_SETUP_CHOICES,
        label="SNMP setup",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            css_class = field.widget.attrs.get('class', '')
            field.widget.attrs['class'] = f"{css_class} form-control".strip()
        self.fields['snmp_community'].required = False
        self.fields['snmp_write_community'].required = False
        if self.instance and self.instance.pk:
            # Show saved credentials on edit; blank submit still keeps old password in clean_password.
            self.fields['username'].initial = self.instance.username
            self.fields['password'].initial = self.instance.password
            self.fields['password'].required = False
            self.fields['password'].help_text = 'Leave blank to keep current password'
            if not self.initial.get('snmp_write_community') and self.instance.snmp_write_community:
                self.fields['snmp_write_community'].initial = self.instance.snmp_write_community
            self.fields['snmp_mode'].initial = 'manual'
        elif not self.is_bound:
            self.fields['snmp_mode'].initial = 'manual'
            self.fields['snmp_community'].initial = ''
            self.fields['snmp_write_community'].initial = ''

    def _build_snmp_read_default(self):
        return generate_snmp_community()

    def _build_snmp_write_default(self):
        return f"{generate_snmp_community()}-rw"

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            return password
        if self.instance and self.instance.pk:
            return self.instance.password
        raise forms.ValidationError('Password is required.')

    def clean_snmp_community(self):
        mode = str(self.cleaned_data.get('snmp_mode') or 'manual').strip().lower()
        value = str(self.cleaned_data.get('snmp_community') or '').strip()
        if value:
            return value
        if mode == 'manual':
            raise forms.ValidationError('SNMP read community is required in manual mode.')
        if self.instance and self.instance.pk and self.instance.snmp_community:
            return self.instance.snmp_community
        return self._build_snmp_read_default()

    def clean_snmp_write_community(self):
        mode = str(self.cleaned_data.get('snmp_mode') or 'manual').strip().lower()
        value = str(self.cleaned_data.get('snmp_write_community') or '').strip()
        if value:
            return value
        if mode == 'manual':
            return ""
        if self.instance and self.instance.pk and self.instance.snmp_write_community:
            return self.instance.snmp_write_community
        return self._build_snmp_write_default()

    class Meta:
        model = OLT
        fields = [
            'name',
            'ip_address',
            'port',
            'snmp_port',
            'snmp_mode',
            'snmp_community',
            'snmp_write_community',
            'username',
            'password',
            'vendor',
            'hardware_version',
        ]
        widgets = {
            'password': forms.PasswordInput(render_value=True),
            'hardware_version': forms.Select(choices=HUAWEI_HARDWARE_CHOICES),
        }
        labels = {
            'port': 'TCP (Telnet)',
            'snmp_port': 'UDP (SNMP)',
            'snmp_mode': 'SNMP setup mode',
            'snmp_community': 'SNMP read community string',
            'snmp_write_community': 'SNMP write community string',
            'hardware_version': 'OLT Hardware Version',
        }
        help_texts = {
            'port': 'Default Telnet port is 23',
            'snmp_port': 'Default SNMP UDP port is 161',
            'snmp_mode': 'Choose manual SNMP strings or auto-generate and push them to the OLT.',
            'snmp_community': 'Auto-generated by Smart OLT if left blank. Used for SNMP polling.',
            'snmp_write_community': 'Auto-generated by Smart OLT if left blank. Pushed to the OLT over Telnet.',
            'hardware_version': 'Select your Huawei OLT hardware model',
        }


class VLANAddForm(forms.Form):
    vlan_id = forms.IntegerField(
        min_value=1,
        max_value=4094,
        label="VLAN ID",
        error_messages={
            "required": "VLAN ID is required.",
            "invalid": "VLAN ID must be a number between 1 and 4094.",
            "min_value": "VLAN ID must be between 1 and 4094.",
            "max_value": "VLAN ID must be between 1 and 4094.",
        },
    )
    description = forms.CharField(
        required=False,
        max_length=20,
        label="Description",
        error_messages={
            "max_length": "Description must be 20 characters or fewer.",
        },
    )
    def __init__(self, *args, **kwargs):
        reserved_ids = kwargs.pop("reserved_ids", None)
        super().__init__(*args, **kwargs)
        self.reserved_ids = {int(value) for value in (reserved_ids or set())}
        for field in self.fields.values():
            css_class = field.widget.attrs.get("class", "")
            field.widget.attrs["class"] = f"{css_class} form-control".strip()
        self.fields["vlan_id"].widget.attrs["placeholder"] = "39"
        self.fields["description"].widget.attrs["placeholder"] = "SM"

    def clean_vlan_id(self):
        vlan_id = int(self.cleaned_data["vlan_id"])
        if vlan_id < 1 or vlan_id > 4094:
            raise forms.ValidationError("VLAN ID must be between 1 and 4094.")
        if vlan_id in self.reserved_ids:
            raise forms.ValidationError("This VLAN already exists on the OLT.")
        return vlan_id

    def clean_description(self):
        description = str(self.cleaned_data.get("description") or "").strip()
        if len(description) > 20:
            raise forms.ValidationError("Description must be 20 characters or fewer.")
        if '"' in description:
            raise forms.ValidationError('Double quotes are not allowed in the description.')
        return description


class VLANBulkAddForm(forms.Form):
    vlan_range = forms.CharField(
        max_length=32,
        label="VLAN Range",
        error_messages={
            "required": "VLAN range is required.",
            "max_length": "VLAN range is too long.",
        },
    )
    def __init__(self, *args, **kwargs):
        reserved_ids = kwargs.pop("reserved_ids", None)
        super().__init__(*args, **kwargs)
        self.reserved_ids = {int(value) for value in (reserved_ids or set())}
        for field in self.fields.values():
            css_class = field.widget.attrs.get("class", "")
            field.widget.attrs["class"] = f"{css_class} form-control".strip()
        self.fields["vlan_range"].widget.attrs["placeholder"] = "150-160"

    def clean_vlan_range(self):
        raw_value = str(self.cleaned_data.get("vlan_range") or "").strip()
        match = re.match(r"^(\d+)\s*-\s*(\d+)$", raw_value)
        if not match:
            raise forms.ValidationError("Enter VLAN range like 150-160.")
        start = int(match.group(1))
        end = int(match.group(2))
        if start < 1 or end > 4094 or start >= end:
            raise forms.ValidationError("VLAN range must stay between 1 and 4094, and end must be greater than start.")
        count = (end - start) + 1
        if count > 11:
            raise forms.ValidationError("You can add up to 11 VLANs at a time.")
        existing = [str(vlan_id) for vlan_id in range(start, end + 1) if vlan_id in self.reserved_ids]
        if existing:
            raise forms.ValidationError(f"These VLANs already exist on the OLT: {', '.join(existing[:6])}")
        return {"raw": f"{start}-{end}", "start": start, "end": end, "count": count}


class SubscriptionPlanForm(forms.ModelForm):
    class Meta:
        model = SubscriptionPlan
        fields = ["name", "billing_mode", "monthly_price", "max_olts", "max_onus", "is_active"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class ClientPanelForm(forms.ModelForm):
    class Meta:
        model = ClientPanel
        fields = [
            "name",
            "contact_name",
            "contact_email",
            "contact_phone",
            "plan",
            "status",
            "monthly_price_override",
            "notes",
        ]
        widgets = {"notes": forms.Textarea(attrs={"rows": 3})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["plan"].queryset = SubscriptionPlan.objects.filter(is_active=True).order_by("name")
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class ControlUserCreateForm(forms.Form):
    ROLE_CHOICES = [
        ("client_admin", "Client Admin"),
        ("viewer", "Viewer"),
    ]
    name = forms.CharField(max_length=120)
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    client_panel = forms.ModelChoiceField(queryset=ClientPanel.objects.none(), required=False)
    role = forms.ChoiceField(choices=ROLE_CHOICES, initial="viewer")
    is_staff = forms.BooleanField(required=False, label="Allow admin/settings access")
    is_active = forms.BooleanField(required=False, initial=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["client_panel"].queryset = ClientPanel.objects.order_by("name")
        for field in self.fields.values():
            css_class = field.widget.attrs.get("class", "")
            field.widget.attrs["class"] = f"{css_class} form-control".strip()
        self.fields["is_staff"].widget.attrs["class"] = ""
        self.fields["is_active"].widget.attrs["class"] = ""


class OLTControlForm(forms.Form):
    client_panel = forms.ModelChoiceField(queryset=ClientPanel.objects.none(), required=False, empty_label="Unassigned")
    service_enabled = forms.BooleanField(required=False, label="OLT active")
    service_disabled_reason = forms.CharField(max_length=255, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["client_panel"].queryset = ClientPanel.objects.order_by("name")
        for field in self.fields.values():
            css_class = field.widget.attrs.get("class", "")
            field.widget.attrs["class"] = f"{css_class} form-control".strip()
        self.fields["service_enabled"].widget.attrs["class"] = ""


