from django.urls import path
from . import views

urlpatterns = [
    path('', views.olt_list, name='olt_list'),
    path('dashboard/status-graph/', views.dashboard_status_graph, name='dashboard_status_graph'),
    path('dashboard/olt-uptimes/', views.dashboard_olt_uptimes, name='dashboard_olt_uptimes'),
    path('snmp/traps/onu/', views.onu_trap_ingest, name='onu_trap_ingest'),
    path('unconfigured/', views.unconfigured_onus, name='unconfigured_onus'),
    path('configured/', views.configured_onus, name='configured_onus'),
    path('configured/signals/refresh/', views.configured_onu_signals_refresh, name='configured_onu_signals_refresh'),
    path('configured/<int:olt_pk>/<int:slot>/<int:port>/<int:ont_id>/', views.configured_onu_detail, name='configured_onu_detail'),
    path('settings/', views.settings_home, name='settings_home'),
    path('settings/olt/', views.olt_settings_olt, name='olt_settings_olt'),
    path('add/', views.olt_add, name='olt_add'),
    path('edit/<int:pk>/', views.olt_edit, name='olt_edit'),
    path('view/<int:pk>/', views.olt_view, name='olt_view'),
    path('view/<int:pk>/details-refresh/', views.olt_details_refresh, name='olt_details_refresh'),
    path('view/<int:pk>/cli-window/', views.olt_cli_window, name='olt_cli_window'),
    path('view/<int:pk>/cli/open/', views.olt_cli_open, name='olt_cli_open'),
    path('view/<int:pk>/cli/run/', views.olt_cli_run, name='olt_cli_run'),
    path('view/<int:pk>/cli/close/', views.olt_cli_close, name='olt_cli_close'),
    path('view/<int:pk>/refresh-ports/', views.olt_refresh_ports, name='olt_refresh_ports'),
    path('view/<int:pk>/refresh-pon-ports/', views.olt_refresh_pon_ports, name='olt_refresh_pon_ports'),
    path('view/<int:pk>/refresh-uplink/', views.olt_refresh_uplink, name='olt_refresh_uplink'),
    path('view/<int:pk>/refresh-vlans/', views.olt_refresh_vlans, name='olt_refresh_vlans'),
    path('view/<int:pk>/add-vlan/', views.olt_add_vlan, name='olt_add_vlan'),
    path('view/<int:pk>/add-vlan-bulk/', views.olt_add_vlan_bulk, name='olt_add_vlan_bulk'),
    path('view/<int:pk>/refresh-profiles/', views.olt_refresh_profiles, name='olt_refresh_profiles'),
    path('view/<int:pk>/add-profile/', views.olt_add_profile, name='olt_add_profile'),
    path('view/<int:pk>/profile-configuration/', views.olt_profile_configuration, name='olt_profile_configuration'),
    path('view/<int:pk>/sync-snmp/', views.olt_sync_snmp_legacy, name='olt_sync_snmp_legacy'),
    path('export/', views.olt_export, name='olt_export'),
    path('delete/<int:pk>/', views.olt_delete, name='olt_delete'),
    path('telnet-connect/<int:pk>/', views.olt_telnet_connect, name='olt_telnet_connect'),
]
