# Generated by Django 5.2.11 on 2026-02-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('vendor', models.CharField(default='Huawei', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
