# Generated by Django 5.2.11 on 2026-04-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0018_olt_dba_profile_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStatusSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_onus', models.PositiveIntegerField(default=0)),
                ('online_onus', models.PositiveIntegerField(default=0)),
                ('offline_onus', models.PositiveIntegerField(default=0)),
                ('admin_disabled', models.PositiveIntegerField(default=0)),
                ('power_failure', models.PositiveIntegerField(default=0)),
                ('loss_of_signal', models.PositiveIntegerField(default=0)),
                ('signal_warn', models.PositiveIntegerField(default=0)),
                ('signal_bad', models.PositiveIntegerField(default=0)),
                ('sampled_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_status_samples', to='oltmanager.olt')),
            ],
            options={
                'ordering': ['sampled_at'],
                'indexes': [models.Index(fields=['olt', 'sampled_at'], name='dash_status_olt_time_idx'), models.Index(fields=['sampled_at'], name='dash_status_time_idx')],
            },
        ),
    ]
