# Generated by Django 5.2.11 on 2026-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0030_olt_attached_vlan_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstatussample',
            name='wait_for_authorize_new_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardstatussample',
            name='wait_for_authorize_resync_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardstatussample',
            name='wait_for_authorize_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
