# Generated by Django 5.2.11 on 2026-04-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0031_dashboardstatussample_wait_for_authorize_new_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='snmp_down_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
