# Generated by Django 5.2.11 on 2026-05-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0034_configuredonu_runtime_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuredonu',
            name='download_profile_index_cache',
        ),
        migrations.RemoveField(
            model_name='configuredonu',
            name='download_profile_name_cache',
        ),
        migrations.RemoveField(
            model_name='configuredonu',
            name='upload_profile_index_cache',
        ),
        migrations.RemoveField(
            model_name='configuredonu',
            name='upload_profile_name_cache',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='dba_profile_cache',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='dba_profile_refreshed_at',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='dba_profile_status',
        ),
    ]
