# Generated by Django 5.2.11 on 2026-05-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0035_remove_configuredonu_download_profile_index_cache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('speed_mbps_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('speed_display', models.CharField(blank=True, default='', max_length=64)),
                ('download_name', models.CharField(blank=True, default='', max_length=160)),
                ('upload_name', models.CharField(blank=True, default='', max_length=160)),
                ('download_command', models.TextField(blank=True, default='')),
                ('upload_command', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['speed_mbps_value', 'name'],
            },
        ),
    ]
