# Generated by Django 5.2.11 on 2026-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0036_speedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedprofile',
            name='index_number',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
