# Generated by Django 5.2.11 on 2026-05-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0047_configuredonu_stability_report_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedprofile',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
