# Generated by Django 5.2.11 on 2026-05-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0048_speedprofile_is_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_recipients', models.TextField(blank=True, default='', help_text='Comma / newline separated email addresses')),
                ('notify_olt_down', models.BooleanField(default=True)),
                ('notify_olt_recovered', models.BooleanField(default=True)),
                ('notify_high_temp', models.BooleanField(default=True)),
                ('notify_subscription', models.BooleanField(default=True)),
                ('temp_threshold_c', models.PositiveIntegerField(default=60)),
                ('renotify_minutes', models.PositiveIntegerField(default=30)),
                ('subscription_warn_days', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=16)),
                ('dedup_key', models.CharField(db_index=True, max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notify_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='oltmanager.olt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'dedup_key'], name='alert_active_key_idx'), models.Index(fields=['is_active', 'created_at'], name='alert_active_time_idx')],
            },
        ),
    ]
