# Generated by Django 5.2.11 on 2026-05-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0049_alertconfig_alertevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='smtp_from',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
