# Generated by Django 5.2.11 on 2026-05-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0050_alertconfig_smtp_from_alertconfig_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='import_onus',
            field=models.BooleanField(default=True),
        ),
    ]
