# Generated by Django 5.2.11 on 2026-06-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0051_olt_import_onus'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuredonu',
            name='configured_via_app',
            field=models.BooleanField(default=False),
        ),
    ]
