# Generated by Django 5.2.11 on 2026-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0052_configuredonu_configured_via_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='fiber_cut_min_onus',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='fiber_cut_ratio',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='notify_fiber_cut',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='notify_signal_degrade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='signal_degrade_drop_db',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
