# Generated by Django 5.2.11 on 2026-07-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0053_alertconfig_fiber_cut_min_onus_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onuopticalsample',
            index=models.Index(fields=['sampled_at'], name='onu_opt_time_idx'),
        ),
        migrations.AddIndex(
            model_name='onustatussample',
            index=models.Index(fields=['sampled_at'], name='onu_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='onutrafficsample',
            index=models.Index(fields=['sampled_at'], name='onu_traf_time_idx'),
        ),
        migrations.AddIndex(
            model_name='ponporttrafficsample',
            index=models.Index(fields=['sampled_at'], name='pon_port_time_idx'),
        ),
        migrations.AddIndex(
            model_name='uplinkporttrafficsample',
            index=models.Index(fields=['sampled_at'], name='uplk_time_idx'),
        ),
    ]
