# Generated by Django 5.2.11 on 2026-07-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0054_sample_time_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertconfig',
            name='notify_subscription',
        ),
        migrations.RemoveField(
            model_name='alertconfig',
            name='subscription_warn_days',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='subscription_ends_at',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='subscription_package_months',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='subscription_started_at',
        ),
    ]
