# Generated by Django 5.2.11 on 2026-07-26 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0055_remove_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('monthly_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('billing_mode', models.CharField(choices=[('fixed', 'Fixed monthly'), ('per_olt', 'Per OLT'), ('per_onu', 'Per ONU')], default='fixed', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_olts', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('max_onus', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['monthly_price', 'name'],
            },
        ),
        migrations.AddField(
            model_name='olt',
            name='service_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='service_disabled_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olt',
            name='service_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='client_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olts', to='oltmanager.clientpanel'),
        ),
        migrations.AddField(
            model_name='clientpanel',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='oltmanager.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client_admin', 'Client Admin'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='oltmanager.clientpanel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='olt_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('details', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oltmanager.clientpanel')),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oltmanager.olt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='control_audit_action_time_idx')],
            },
        ),
    ]
