# Generated by Django 5.2.11 on 2026-07-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0056_clientpanel_subscriptionplan_olt_service_disabled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpanel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='controlauditlog',
            name='client_panel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='client_panel',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='client_panel',
        ),
        migrations.RemoveField(
            model_name='controlauditlog',
            name='olt',
        ),
        migrations.RemoveField(
            model_name='controlauditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='service_disabled_at',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='service_disabled_reason',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='service_enabled',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='ClientPanel',
        ),
        migrations.DeleteModel(
            name='ControlAuditLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
