# Generated by Django 5.2.11 on 2026-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0057_remove_clientpanel_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='pricing_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='pricing_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='olt',
            name='pricing_locked_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olt',
            name='pricing_mode',
            field=models.CharField(choices=[('demo', 'Demo Account'), ('standard', 'Standard (1 month)'), ('custom', 'Custom')], db_index=True, default='standard', max_length=20),
        ),
    ]
