# Generated by Django 5.2.11 on 2026-08-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0058_olt_pricing_expires_at_olt_pricing_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onuopticalsample',
            name='sample_source',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('carried', 'Carried'), ('single_retry', 'Single retry'), ('stale', 'Stale')], db_index=True, default='fresh', max_length=16),
        ),
    ]
