# Generated by Django 5.2.11 on 2026-08-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0060_configuredonu_mapping_mode_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuredonu',
            name='catv_operational_cache',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
