# Generated by Django 5.2.11 on 2026-09-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0061_configuredonu_catv_operational_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('client_public_ip', models.GenericIPAddressField(help_text='Client-side public/static IP for the VPN peer.')),
                ('client_vpn_port', models.PositiveIntegerField(default=51820)),
                ('client_local_subnet', models.CharField(help_text='Client LAN subnet, e.g. 192.168.10.0/24.', max_length=64)),
                ('olt_management_subnet', models.CharField(blank=True, default='', help_text='OLT reachable subnet, e.g. 10.101.11.0/24.', max_length=64)),
                ('wg_server_endpoint', models.CharField(help_text='VPS WireGuard endpoint, e.g. vpn.example.com:51820.', max_length=160)),
                ('wg_server_public_key', models.CharField(blank=True, default='', max_length=120)),
                ('wg_client_address', models.CharField(blank=True, default='', max_length=64)),
                ('wg_client_private_key', models.CharField(blank=True, default='', max_length=120)),
                ('wg_client_public_key', models.CharField(blank=True, default='', max_length=120)),
                ('agent_token', models.CharField(max_length=128, unique=True)),
                ('docker_image', models.CharField(default='optiverse-agent:latest', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('config_ready', 'Config ready'), ('agent_online', 'Agent online'), ('vpn_online', 'VPN online')], db_index=True, default='config_ready', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
