# Generated by Django 5.2.11 on 2026-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltmanager', '0062_tenantprovisioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprovisioning',
            name='container_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenantprovisioning',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprovisioning',
            name='provisioning_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantprovisioning',
            name='provisioning_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantprovisioning',
            name='wg_config_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
