# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oltmanager", "0063_tenantprovisioning_container_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="configuredonu",
            index=models.Index(fields=["olt", "derived_status"], name="conf_onu_olt_status_idx"),
        ),
        migrations.AddIndex(
            model_name="configuredonu",
            index=models.Index(fields=["derived_status", "signal_bucket", "olt"], name="conf_onu_status_signal_idx"),
        ),
        migrations.AddIndex(
            model_name="configuredonu",
            index=models.Index(fields=["olt", "signal_bucket"], name="conf_onu_olt_signal_idx"),
        ),
    ]
