# Generated by Django 5.2.11 on 2026-07-26 08:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('billing_mode', models.CharField(choices=[('fixed', 'Fixed monthly'), ('per_olt', 'Per OLT'), ('per_onu', 'Per ONU')], default='fixed', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_olts', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('max_onus', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['monthly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('isp_name', models.CharField(blank=True, default='', max_length=160)),
                ('owner_name', models.CharField(blank=True, default='', max_length=120)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('owner_phone', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('provisioning', 'Provisioning'), ('disabled', 'Disabled')], db_index=True, default='provisioning', max_length=20)),
                ('monthly_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('panel_scheme', models.CharField(default='http', max_length=10)),
                ('panel_host', models.CharField(blank=True, default='', max_length=160)),
                ('panel_port', models.PositiveIntegerField(default=8000)),
                ('panel_base_path', models.CharField(blank=True, default='', max_length=120)),
                ('codebase_path', models.CharField(blank=True, default='', max_length=255)),
                ('database_path', models.CharField(blank=True, default='', max_length=255)),
                ('env_path', models.CharField(blank=True, default='', max_length=255)),
                ('service_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_known_olt_count', models.PositiveIntegerField(default=0)),
                ('last_known_onu_count', models.PositiveIntegerField(default=0)),
                ('last_known_db_size_mb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='controlmanager.plan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Panel Admin'), ('billing', 'Billing'), ('tech', 'Technical')], default='admin', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='controlmanager.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olt_count', models.PositiveIntegerField(default=0)),
                ('onu_count', models.PositiveIntegerField(default=0)),
                ('db_size_mb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('app_version', models.CharField(blank=True, default='', max_length=80)),
                ('status_note', models.CharField(blank=True, default='', max_length=255)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='controlmanager.tenant')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('details', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlmanager.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='cp_audit_action_time_idx')],
            },
        ),
    ]
