# Generated by Django 5.2.11 on 2026-07-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='panel_admin_initial_password',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='tenant',
            name='panel_admin_username',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='TenantOLTSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_olt_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=160)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('hardware_version', models.CharField(blank=True, default='', max_length=100)),
                ('sw_version', models.CharField(blank=True, default='', max_length=100)),
                ('snmp_last_status', models.CharField(blank=True, default='', max_length=300)),
                ('onu_count', models.PositiveIntegerField(default=0)),
                ('online_count', models.PositiveIntegerField(default=0)),
                ('offline_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olt_snapshots', to='controlmanager.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
                'unique_together': {('tenant', 'tenant_olt_id')},
            },
        ),
    ]
