# Generated by Django 5.2.11 on 2026-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmanager', '0002_tenant_panel_admin_initial_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='agent_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tenant',
            name='client_local_subnet',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='client_public_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='client_vpn_port',
            field=models.PositiveIntegerField(default=51820),
        ),
        migrations.AddField(
            model_name='tenant',
            name='container_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='docker_image',
            field=models.CharField(default='optiverse-agent:latest', max_length=160),
        ),
        migrations.AddField(
            model_name='tenant',
            name='olt_management_subnet',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='provisioning_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='provisioning_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wg_client_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wg_client_private_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wg_client_public_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wg_config_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wg_server_endpoint',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wg_server_public_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
