# Generated by Django 5.2.16 on 2026-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmanager', '0003_tenant_agent_token_tenant_client_local_subnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='worker_container_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
