# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmanager', '0004_tenant_worker_container_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='docker_image',
            field=models.CharField(default='optiverse-tenant-app:latest', max_length=160),
        ),
    ]
