# Generated by Django 5.2.11 on 2026-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmanager', '0005_tenant_docker_image_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='public_hostname',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.SlugField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vpn_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vpn_listen_port',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vpn_routes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vpn_server_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vpn_server_private_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('subdomain', ''), _negated=True), fields=('subdomain',), name='unique_nonempty_tenant_subdomain'),
        ),
    ]
