# Generated by Django 5.2.11 on 2026-09-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlmanager', '0007_tenant_vpn_address_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='docker_image',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='worker_container_name',
        ),
    ]
