# Generated by Django 5.2.11 on 2026-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmanager', '0008_remove_tenant_container_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='database_engine',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL')], default='postgresql', max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_host',
            field=models.CharField(default='127.0.0.1', max_length=160),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_name',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_password',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_port',
            field=models.PositiveIntegerField(default=5432),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_user',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
