"""
Django settings for oltportal project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env(path):
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_local_env(BASE_DIR / ".env")


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=None):
    raw_value = os.environ.get(name)
    if raw_value is None:
        return list(default or [])
    return [part.strip() for part in raw_value.split(",") if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-this-before-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    ["127.0.0.1", "localhost", "10.101.11.22"],
)
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [])
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", False)
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oltmanager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oltportal.urls'
ASGI_APPLICATION = 'oltportal.routing.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oltportal.wsgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_DB_PATH', str(BASE_DIR / 'db.sqlite3')),
        'OPTIONS': {
            'timeout': int(os.environ.get('SQLITE_TIMEOUT_SECONDS', '30')),
        },
    }
}

OLT_SAMPLE_RETENTION_DAYS = {
    'onu_optical': int(os.environ.get('OLT_ONU_OPTICAL_RETENTION_DAYS', '15')),
    'onu_status': int(os.environ.get('OLT_ONU_STATUS_RETENTION_DAYS', '30')),
    'onu_traffic': int(os.environ.get('OLT_ONU_TRAFFIC_RETENTION_DAYS', '30')),
    'pon_traffic': int(os.environ.get('OLT_PON_TRAFFIC_RETENTION_DAYS', '30')),
    'pon_port_traffic': int(os.environ.get('OLT_PON_PORT_TRAFFIC_RETENTION_DAYS', '30')),
    'uplink_port_traffic': int(os.environ.get('OLT_UPLINK_PORT_TRAFFIC_RETENTION_DAYS', '30')),
    'dashboard_status': int(os.environ.get('OLT_DASHBOARD_STATUS_RETENTION_DAYS', '180')),
}
OLT_ONU_OPTICAL_SAMPLE_INTERVAL_SECONDS = int(os.environ.get('OLT_ONU_OPTICAL_SAMPLE_INTERVAL_SECONDS', '3600'))
OLT_SAMPLE_RETENTION_BATCH_SIZE = int(os.environ.get('OLT_SAMPLE_RETENTION_BATCH_SIZE', '5000'))
OLT_SAMPLE_RETENTION_MAX_BATCHES_PER_MODEL = int(os.environ.get('OLT_SAMPLE_RETENTION_MAX_BATCHES_PER_MODEL', '4'))
OLT_SAMPLE_RETENTION_CLEANUP_SECONDS = int(os.environ.get('OLT_SAMPLE_RETENTION_CLEANUP_SECONDS', '3600'))


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'en-us')

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Asia/Karachi')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'olt_list'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Email (alerts) SENDER — configured ONCE by the provider/installer, NOT by the
# end customer. Customers only choose recipient addresses in Settings > Alerts.
#
# Recommended: a transactional e-mail service (great deliverability, free tiers,
# no Gmail "app password" hassle). Set these env vars at deploy time, e.g.:
#
#   Brevo (Sendinblue):
#     OLT_EMAIL_HOST=smtp-relay.brevo.com  OLT_EMAIL_PORT=587  OLT_EMAIL_USE_TLS=true
#     OLT_EMAIL_USER=<brevo-login>  OLT_EMAIL_PASSWORD=<brevo-smtp-key>
#     OLT_EMAIL_FROM="OptiVerse Alerts <alerts@yourdomain.com>"
#
#   SendGrid:  host smtp.sendgrid.net, user "apikey", password=<api-key>
#   Amazon SES: host email-smtp.<region>.amazonaws.com, SES SMTP creds
#
# Local testing without any server (prints e-mails to the console):
#   OLT_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# ---------------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get(
    'OLT_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('OLT_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('OLT_EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('OLT_EMAIL_USE_TLS', 'true').strip().lower() in {'1', 'true', 'yes'}
EMAIL_USE_SSL = os.environ.get('OLT_EMAIL_USE_SSL', 'false').strip().lower() in {'1', 'true', 'yes'}
EMAIL_HOST_USER = os.environ.get('OLT_EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('OLT_EMAIL_PASSWORD', '')
EMAIL_TIMEOUT = int(os.environ.get('OLT_EMAIL_TIMEOUT', '20'))
DEFAULT_FROM_EMAIL = os.environ.get(
    'OLT_EMAIL_FROM', EMAIL_HOST_USER or 'OptiVerse Alerts <alerts@optiverse.local>'
)
